import = [
    "~/.config/alacritty/catppuccin-latte.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "full"
dynamic_title = false
opacity = 1
title = "ğŸ”ï¸"

[window.padding]
x = 6
y = 6
